'use client'

import { useMemo, useState } from 'react'
import { AlertTriangle, ArrowRight, CalendarDays, CheckCircle2, CircleDollarSign, FileText, RefreshCw, Scale, ShieldAlert, Sparkles } from 'lucide-react'

const money = (n: number) => `₹${(n / 100000).toFixed(2)}L`

export function PhaseTwoDashboard() {
  const [taxView, setTaxView] = useState<'realized' | 'harvest'>('realized')
  const [targetEquity, setTargetEquity] = useState(60)
  const currentEquity = 61
  const gap = targetEquity - currentEquity
  const tax = taxView === 'realized' ? 18400 : 7200
  const actions = useMemo(() => gap > 3 ? ['Increase diversified equity only through new contributions', 'Avoid adding to the most concentrated single-stock position', 'Recheck allocation after the next statement import'] : gap < -3 ? ['Direct new contributions toward fixed income or cash reserves', 'Review exit taxes before reducing equity', 'Do not rebalance solely because of a short-term market move'] : ['Your current mix is within the selected target range', 'Use new contributions to maintain the range', 'Review concentration before adding to existing names'], [gap])
  return <div className="mt-7 overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="border-b border-border bg-slate-950 px-5 py-5 text-white md:px-7"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.18em] text-teal-300"><Sparkles size={14}/> Phase 2 intelligence</div><h2 className="mt-2 text-2xl font-semibold tracking-tight">Tax, events, and rebalancing coach</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-white/65">Turn portfolio data into decisions with visible assumptions, event context, and guardrails. These are educational estimates, not tax or investment advice.</p></div><Scale className="text-teal-300" size={22}/></div></div><div className="grid gap-4 p-5 md:p-7 xl:grid-cols-3"><TaxCenter taxView={taxView} setTaxView={setTaxView} tax={tax}/><EventRadar/><RebalanceCoach targetEquity={targetEquity} setTargetEquity={setTargetEquity} gap={gap} actions={actions}/></div></div>
}
function TaxCenter({ taxView, setTaxView, tax }: { taxView: 'realized'|'harvest'; setTaxView: (v: 'realized'|'harvest') => void; tax: number }) { return <section className="rounded-xl border border-border p-5"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold text-primary"><CircleDollarSign size={16}/> India tax center</div><p className="mt-1 text-xs text-muted-foreground">Estimate only; verify with your CA and complete transaction history.</p></div><FileText size={17} className="text-muted-foreground"/></div><div className="mt-4 flex rounded-md border border-input text-[10px] font-semibold"><button onClick={() => setTaxView('realized')} className={`flex-1 px-2 py-2 ${taxView === 'realized' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'}`}>Realized estimate</button><button onClick={() => setTaxView('harvest')} className={`flex-1 border-l border-input px-2 py-2 ${taxView === 'harvest' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'}`}>Harvest review</button></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-lg bg-muted p-3"><div className="text-[10px] uppercase tracking-wider text-muted-foreground">Estimated tax</div><div className="mt-1 font-mono text-xl font-bold text-primary">{money(tax)}</div></div><div className="rounded-lg bg-teal-50 p-3"><div className="text-[10px] uppercase tracking-wider text-teal-800">Data status</div><div className="mt-1 text-sm font-semibold text-teal-900">Partial</div></div></div><div className="mt-4 space-y-2 text-xs leading-5 text-muted-foreground"><p><strong className="text-primary">Short-term:</strong> needs dated purchase and sale lots.</p><p><strong className="text-primary">Long-term:</strong> rate and exemption treatment depends on asset and transaction date.</p><p><strong className="text-primary">Next step:</strong> import broker/CAS statements before acting.</p></div></section> }
function EventRadar() { return <section className="rounded-xl border border-border p-5"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold text-primary"><CalendarDays size={16}/> Event radar</div><p className="mt-1 text-xs text-muted-foreground">Events to verify against official company or issuer notices.</p></div><RefreshCw size={16} className="text-muted-foreground"/></div><div className="mt-4 space-y-3"><Event date="18 Sep" title="Quarterly results" detail="Review revenue, margin, and management commentary" tone="teal"/><Event date="24 Sep" title="Dividend record date" detail="Confirm eligibility and expected cash flow" tone="amber"/><Event date="30 Sep" title="Bond coupon watch" detail="Check issuer notice and maturity schedule" tone="slate"/></div><button className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-primary underline underline-offset-4">Open event checklist <ArrowRight size={13}/></button></section> }
function Event({ date, title, detail, tone }: { date: string; title: string; detail: string; tone: 'teal'|'amber'|'slate' }) { const colors = tone === 'teal' ? 'bg-teal-50 text-teal-900' : tone === 'amber' ? 'bg-amber-50 text-amber-950' : 'bg-muted text-primary'; return <div className={`rounded-lg p-3 ${colors}`}><div className="flex gap-3"><div className="w-12 shrink-0 font-mono text-[10px] font-bold">{date}</div><div><div className="text-xs font-semibold">{title}</div><div className="mt-1 text-[10px] leading-4 opacity-75">{detail}</div></div></div></div> }
function RebalanceCoach({ targetEquity, setTargetEquity, gap, actions }: { targetEquity: number; setTargetEquity: (n: number) => void; gap: number; actions: string[] }) { const status = Math.abs(gap) <= 3 ? 'Within range' : gap > 0 ? 'Below target' : 'Above target'; return <section className="rounded-xl border border-border p-5"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold text-primary"><Scale size={16}/> Rebalancing coach</div><p className="mt-1 text-xs text-muted-foreground">Ranges, not forced trades. Consider taxes and liquidity first.</p></div><ShieldAlert size={17} className="text-amber-600"/></div><label className="mt-5 block text-xs font-medium text-primary">Target equity allocation <span className="float-right font-mono">{targetEquity}%</span><input aria-label="Target equity allocation" type="range" min="20" max="90" step="5" value={targetEquity} onChange={e => setTargetEquity(Number(e.target.value))} className="mt-3 w-full accent-teal-600"/></label><div className="mt-4 flex items-center justify-between rounded-lg bg-muted p-3"><div><div className="text-[10px] uppercase tracking-wider text-muted-foreground">Coach status</div><div className="mt-1 text-sm font-semibold text-primary">{status}</div></div><div className={`font-mono text-lg font-bold ${Math.abs(gap) <= 3 ? 'text-teal-700' : 'text-amber-800'}`}>{gap > 0 ? '+' : ''}{gap}%</div></div><ul className="mt-4 space-y-2 text-xs leading-5 text-muted-foreground">{actions.map(action => <li key={action} className="flex gap-2"><CheckCircle2 className="mt-0.5 shrink-0 text-teal-600" size={13}/>{action}</li>)}</ul><div className="mt-4 flex gap-2 rounded-lg border border-amber-300/70 bg-amber-50 p-3 text-[10px] leading-4 text-amber-950"><AlertTriangle className="mt-0.5 shrink-0" size={13}/> Never rebalance from this panel without checking exit taxes, bid-ask spreads, lock-ins, and your written investment plan.</div></section> }
