'use client'

import { useState } from 'react'
import { AlertTriangle, CheckCircle2, FileSpreadsheet, Upload, XCircle } from 'lucide-react'

type Holding = { symbol: string; quantity: number; averagePrice: number | null; currentPrice: number | null; value: number; sector: string; assetClass: string; weight: number; pnl: number | null }
type Report = { score: number; totalValue: number; holdings: Holding[]; strengths: string[]; improvements: string[]; avoid: string[]; warnings: string[]; exposures: { label: string; value: number }[]; dataQuality: number; disclaimer: string }
const money = (n: number) => `₹${n.toLocaleString('en-IN', { maximumFractionDigits: 0 })}`

export function PortfolioAnalyzer() {
  const [file, setFile] = useState<File | null>(null)
  const [report, setReport] = useState<Report | null>(null)
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  async function analyze() {
    if (!file) return
    setLoading(true); setError(''); setReport(null)
    const body = new FormData(); body.append('file', file)
    try { const response = await fetch('/api/portfolio/analyze', { method: 'POST', body }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Could not analyze workbook'); setReport(data) }
    catch (e) { setError(e instanceof Error ? e.message : 'Could not analyze workbook') } finally { setLoading(false) }
  }
  return <section className="mb-6 rounded-xl border border-border bg-card p-5 shadow-sm">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.16em] text-primary"><FileSpreadsheet size={14}/> Portfolio intelligence</div><h2 className="mt-1 text-xl font-semibold text-primary">Import your portfolio</h2><p className="mt-1 max-w-2xl text-xs leading-5 text-muted-foreground">Upload an .xlsx file to receive a transparent portfolio score, concentration review, improvement areas, and a list of behaviours to avoid.</p></div><div className="flex items-center gap-2"><label className="flex cursor-pointer items-center gap-2 rounded-md border border-input px-3 py-2 text-xs font-semibold hover:bg-muted"><Upload size={14}/> {file ? file.name : 'Choose Excel'}<input type="file" accept=".xlsx" className="sr-only" onChange={(e) => { setFile(e.target.files?.[0] ?? null); setReport(null); setError('') }}/></label><button onClick={analyze} disabled={!file || loading} className="rounded-md bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground disabled:opacity-50">{loading ? 'Analyzing…' : 'Analyze portfolio'}</button></div></div>
    <div className="mt-3 text-[10px] text-muted-foreground">Expected columns: Symbol/Ticker, Quantity, Average Buy Price, Current Price or Current Value, Sector, Asset Class. Your workbook is processed server-side and not made public.</div>
    {error && <div className="mt-4 flex items-start gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-800"><XCircle size={15} className="mt-0.5 shrink-0"/>{error}</div>}
    {report && <PortfolioReport report={report}/>} 
  </section>
}
function PortfolioReport({ report }: { report: Report }) { return <div className="mt-6 border-t border-border pt-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Score label="Portfolio score" value={`${report.score}/100`} tone={report.score >= 70 ? 'good' : report.score >= 50 ? 'warn' : 'bad'}/><Score label="Total value" value={money(report.totalValue)} tone="plain"/><Score label="Data quality" value={`${report.dataQuality}%`} tone="plain"/><Score label="Holdings" value={`${report.holdings.length}`} tone="plain"/></div><div className="mt-5 grid gap-5 lg:grid-cols-3"><Advice title="What is working" items={report.strengths} tone="good"/><Advice title="Areas to improve" items={report.improvements} tone="warn"/><Advice title="What to avoid" items={report.avoid} tone="bad"/></div>{report.warnings.length > 0 && <div className="mt-5 rounded-lg border border-amber-300/70 bg-amber-50 p-4"><div className="flex items-center gap-2 text-xs font-semibold text-amber-900"><AlertTriangle size={14}/> Risk flags</div><ul className="mt-2 space-y-1 text-xs leading-5 text-amber-950">{report.warnings.map((item) => <li key={item}>• {item}</li>)}</ul></div>}<div className="mt-5 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-lg border border-border p-4"><h3 className="text-xs font-semibold text-primary">Exposure map</h3><div className="mt-3 space-y-3">{report.exposures.map((item) => <div key={item.label}><div className="mb-1 flex justify-between text-[11px]"><span>{item.label}</span><span className="font-mono">{item.value.toFixed(1)}%</span></div><div className="h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-teal-500" style={{ width: `${Math.min(item.value, 100)}%` }}/></div></div>)}</div></div><div className="overflow-x-auto rounded-lg border border-border"><table className="w-full text-left text-xs"><thead className="border-b border-border bg-muted/50 text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="p-3">Holding</th><th className="p-3">Value</th><th className="p-3">Weight</th><th className="p-3">P&L</th></tr></thead><tbody>{report.holdings.map((h) => <tr key={h.symbol} className="border-b border-border last:border-0"><td className="p-3"><div className="font-semibold text-primary">{h.symbol}</div><div className="text-[10px] text-muted-foreground">{h.sector} · {h.assetClass}</div></td><td className="p-3 font-mono">{money(h.value)}</td><td className="p-3 font-mono">{h.weight.toFixed(1)}%</td><td className={`p-3 font-mono ${h.pnl != null && h.pnl >= 0 ? 'text-teal-700' : 'text-amber-700'}`}>{h.pnl == null ? '—' : `${h.pnl >= 0 ? '+' : ''}${h.pnl.toFixed(1)}%`}</td></tr>)}</tbody></table></div></div><p className="mt-4 text-[10px] leading-4 text-muted-foreground">{report.disclaimer}</p></div> }
function Score({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className="rounded-lg border border-border p-4"><div className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</div><div className={`mt-1 font-mono text-xl font-bold ${tone === 'good' ? 'text-teal-700' : tone === 'warn' ? 'text-amber-700' : tone === 'bad' ? 'text-red-700' : 'text-primary'}`}>{value}</div></div> }
function Advice({ title, items, tone }: { title: string; items: string[]; tone: string }) { return <div className="rounded-lg border border-border p-4"><div className="flex items-center gap-2 text-xs font-semibold text-primary">{tone === 'good' ? <CheckCircle2 size={14} className="text-teal-600"/> : tone === 'bad' ? <XCircle size={14} className="text-red-600"/> : <AlertTriangle size={14} className="text-amber-600"/>}{title}</div><ul className="mt-3 space-y-2 text-xs leading-5 text-muted-foreground">{items.map((item) => <li key={item}>• {item}</li>)}</ul></div> }
